name: Build and Deploy to cPanel (SFTP)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_BASE: ${{ secrets.VITE_BASE }}
        run: npm run build

      - name: Deploy dist over SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: dist/*
          remote_path: ${{ secrets.SFTP_REMOTE_DIR }}
          delete_remote_files: false
